name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start services with Docker Compose
        run: |
          docker compose up -d --build

      - name: Run tests
        run: |
          mvn clean test

      - name: Stop and clean up Docker Compose
        if: always()
        run: |
          docker compose down